project:
  type: manuscript
  output-dir: docs

date: today

manuscript:
  article: index.qmd
  code-links:
   - repo

repo-url: https://github.com/gbv/validation-error-format

resources:
  - schema.json

format:
  html:
    highlight-style: kate
    notebook-links: false
    number-sections: true
    number-depth: 2
    css: style.css
    crossref:
      lst-prefix: "Example"
      lst-title: "Example"
    lst-cap-location: bottom
